---
Name: local-default
---

# This is used to configure the permissions for assets, specifically when building from the command line.

SilverStripe\Assets\Flysystem\PublicAssetAdapter:
  server_configuration:
    php:
      '.htaccess': "SilverStripe\\Assets\\Flysystem\\PublicAssetAdapter_HTAccess"

# This is used to configure the permissions for *protected* assets, specifically when building from the command line.

SilverStripe\Assets\Flysystem\ProtectedAssetAdapter:
  server_configuration:
    php:
      '.htaccess': "SilverStripe\\Assets\\Flysystem\\ProtectedAssetAdapter_HTAccess"
---
Name: local-custom
---


---
Name: dev_log
Before:
  - '*'
---
SilverStripe\Core\Injector\Injector:
  LogFileHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "mysite/silverstripe.log"
      - "info"

